jenkins , docker and openshift set up

diff --git a/springboot-openshift-jenkins-master/Jenkinsfile b/springboot-openshift-jenkins-master/Jenkinsfile
--- a/springboot-openshift-jenkins-master/Jenkinsfile
+++ b/springboot-openshift-jenkins-master/Jenkinsfile
@@ -1,13 +1,6 @@
-/* 
-  assumes build and deployment configurations have been created beforehand as below:
-
-  oc new-build --binary=true --name=spring-demo-bake registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.3 --to=spring-demo
-  oc new-app --image-stream spring-demo --name=spring-demo-dev
-  oc expose dc spring-demo-dev
-  oc set env dc spring-demo-dev JAVA_OPTIONS="-Dmanagement.endpoints.jmx.exposure.include=health,info"
-  oc set probe dc spring-demo-dev --readiness --get-url=http://:8080/health
-  oc set probe dc spring-demo-dev --liveness --get-url=http://:8080/health
-*/
+def projectName = 'dfoodh-dev'
+def version = "0.0.${currentBuild.number}"
+def dockerImageTag = "${projectName}:${version}"
 
 def appName = "${params.PROJECT_NAME}"
 def imageBuildConfig = appName
@@ -30,32 +23,28 @@ pipeline {
       }
     }
 
-    stage('Build') {
+    
+    stage('Build Image') {
       steps {
-        echo "Build artifact"
-        sh 'mvn package'
-        echo "Trigger image build"
-        script {
-          openshift.withCluster() {
-            openshift.selector("bc", imageBuildConfig).startBuild("--from-file=target/ROOT.jar", "--wait")
-            }
-          }
+        dir("springboot-backend"){
+           sh "docker build -t ${dockerImageTag} ."
         }
-      post {
-        success {
-          archiveArtifacts artifacts: 'target/**.jar', fingerprint: true
-        }
+
       }
     }
 
-    stage('Deploy') {
+    stage('Deploy Container To Openshift') {
       steps {
-        script {
-          openshift.withCluster() {
-            openshift.selector("dc", deploymentConfig).rollout()
-          }
-        }
+        sh "oc login https://localhost:8443 --username admin --password admin --insecure-skip-tls-verify=true"
+        sh "oc project ${projectName} || oc new-project ${projectName}"
+        sh "oc delete all --selector app=${projectName} || echo 'Unable to delete all previous openshift resources'"
+        sh "oc new-app ${dockerImageTag} -l version=${version}"
+        sh "oc expose svc ${projectName}"
       }
     }
+
+    
+
+ 
   }
 }
